# Generated by Django 5.2.8 on 2025-11-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('genres', models.JSONField(default=list)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('age_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('clerk_id', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('max_age_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_langs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('genres', models.JSONField(default=list)),
                ('mood_tags', models.JSONField(default=list)),
                ('pace', models.CharField(blank=True, max_length=50, null=True)),
                ('violence_level', models.CharField(blank=True, max_length=50, null=True)),
                ('runtime_pref', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='movies.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='movies.user')),
            ],
        ),
    ]
